[project]
name = "base-django"
version = "0.1.0"
description = ""
authors = [
    {name = "Vlad",email = "vlad-labytin@yandex.ru"}
]
readme = "README.md"
requires-python = "^3.14"
dependencies = [
    "django (>=6.0.4,<7.0.0)",
    "django-redis (>=7.0.0,<8.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "redis (==4.5.5)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "ruff (>=0.15.17,<0.16.0)"
]
