# Generated by Django 6.0.4 on 2026-06-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_owner_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
