# Generated by Django 6.0.4 on 2026-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mailing",
            old_name="date_first",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="date_last",
            new_name="start_time",
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Завершена"),
                    ("Created", "Создана"),
                    ("Running", "Запущена"),
                ],
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
